### ISSUE TITLE
tests failure: AttributeError: module 'sphinx.writers' has no attribute 'text'

### ISSUE THREAD

**Issue by sandrotosi** [AmatanHead/sphinx-a4doc#10]
Hello, when running tests against for sphinx-a4doc/1.2.4 using sphinx/3.3.1 i get this error:

```
sphinx_a4doc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: sphinx_a4doc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sphinx_a4doc
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/build/sphinx-a4doc-1.2.4/.pybuild/cpython3_3.9_sphinx-a4doc/build/sphinx_a4doc/__init__.py", line 6, in <module>
    from sphinx_a4doc.diagram_directive import RailroadDiagramNode, RailroadDiagram, LexerRuleDiagram, ParserRuleDiagram
  File "/build/sphinx-a4doc-1.2.4/.pybuild/cpython3_3.9_sphinx-a4doc/build/sphinx_a4doc/diagram_directive.py", line 93, in <module>
    class RailroadDiagramNode(docutils.nodes.Element, docutils.nodes.General):
  File "/build/sphinx-a4doc-1.2.4/.pybuild/cpython3_3.9_sphinx-a4doc/build/sphinx_a4doc/diagram_directive.py", line 112, in RailroadDiagramNode
    def visit_node_text(self: sphinx.writers.text.TextTranslator, node):
AttributeError: module 'sphinx.writers' has no attribute 'text'
```

**Comment by AmatanHead** [comment]
This looks like an error in a type hint. Can you see if you can reproduce it with python 3.7 and 3.8?

**Comment by sandrotosi** [comment]
In Debian (unstable, where i am running the tests) we no longer support python3.8, so the only environment i have is python3.9

**Comment by sandrotosi** [comment]
is there any fix planned for this?
